networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge
  internal-net:
    driver: bridge
  database-net:
    driver: bridge

volumes:
  pgadmin-data:
    driver: local
  kafka-data:
    driver: local
  timescale-data:
    driver: local
  postgres-data:
    driver: local
  kafka-secrets:
    driver: local
  kafka-config:
    driver: local

services:
  database-service:
    image: timescale/timescaledb:latest-pg17
    container_name: database-service-pdm
    restart: unless-stopped

    depends_on:
      - "broker-service"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${TSDB_USER}
      POSTGRES_PASSWORD: ${TSDB_PASSWORD}
      POSTGRES_DB: ${TSDB_NAME}
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TSDB_USER} -d ${TSDB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    command: >
      postgres
        -c shared_buffers=512MB
        -c max_connections=200
        -c max_wal_size=1GB
        -c timescaledb.max_background_workers=4

    shm_size: '256mb'
    networks:
      - database-net
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "timescale-data:/home/postgres/pgdata/data"
      # - "./prediction-ts-init-db:/docker-entrypoint-initdb.d"

  pg-admin:
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADM_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADM_PASSWORD}
      PGADMIN_LISTEN_PORT: 8100

    ports:
      - "9100:8100"
    
    networks:
      - database-net

    volumes:
      - "pgadmin-data:/var/lib/pgadmin"

  broker-service:
    image: apache/kafka:4.3.1
    container_name: broker-service-pdm
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"

    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "broker-service:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker-service:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093, EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-service:9092, EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT, EXTERNAL:PLAINTEXT, PLAINTEXT:PLAINTEXT
      
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_HEAP_OPTS: -Xms512M -Xmx1G

    networks:
      - backend-net
      - database-net
      - internal-net
    
    volumes:
      - "kafka-data:/var/lib/kafka/data"
      - "kafka-secrets:/etc/kafka/secrets"
      - "kafka-config:/mnt/shared/config"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-pdm
    restart: unless-stopped

    ports:
      - "9108:8088"
    
    depends_on:
      broker-service:
        condition: service_healthy

    networks:
      - internal-net

    environment:
      SERVER_PORT: 8088

      AUTH_TYPE: LOGIN_FORM
      SPRING_SECURITY_USER_NAME: ${KFUI_USER}
      SPRING_SECURITY_USER_PASSWORD: ${KFUI_PASSWORD}

      KAFKA_CLUSTERS_0_NAME: Local DEV Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-service:9092


    

